### ISSUE TITLE
Can i get the DB schema and installation steps ?

### ISSUE THREAD

**Issue by balamgit** [devleaks/golfleague#1]

**Comment by devleaks** [comment]
Hi,
I started looking for it. It might take a while. I haven't touched this software for years.
If I find it, I'll send you the mysql schema of the database.
Best regards.
P.

**Comment by devleaks** [comment]
All right. Here is the database schema. I do not provide any support.
Installation is easy if you're familiar with Yii/php.
If you don't know yii, first learn it. You won't understand anything without knowing yii.
1. git clone this repository
2. use standard Yii / PHP Composer to install dependencies
3. set up standard Yii config (in config dir, set database, etc.)
4. load this schema and data into database
This should work.
Please
[dump-golfleague-202211171018.sql.zip](https://github.com/devleaks/golfleague/files/10029870/dump-golfleague-202211171018.sql.zip)

**Comment by balamgit** [comment]
Thank you so much!
